# -*- coding: utf-8 -*-
"""coal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sGHkibAnpTkEwYyXzJ8KBVUB0k8rPF8g
"""

import time
from gurobipy import GRB, Model

# === data ===

capacity_in_supplier = {'supplier1': 120, 'supplier2': 100, 'supplier3': 80}

shipping_cost_from_supplier_to_factory = {
    ('supplier1', 'factory1'): 4,
    ('supplier1', 'factory2'): 6,
    ('supplier2', 'factory1'): 5,
    ('supplier2', 'factory2'): 3,
    ('supplier3', 'factory1'): 7,
    ('supplier3', 'factory2'): 4
}

cost_negatif = {'factory1': 39.39, 'factory2': 39.39}
cost_pozitif = {'factory1': 39.39, 'factory2': 39.39}

customers = ['fiat_35_nc', 'isuzu_24v']

shipping_cost_from_factory_to_customer = {
    ('factory1', 'fiat_35_nc'): 4,
    ('factory1', 'isuzu_24v'): 6,
    ('factory2', 'fiat_35_nc'): 5,
    ('factory2', 'isuzu_24v'): 4,
}

negatif_needed_for_customer = {
    'fiat_35_nc': 50,
    'isuzu_24v': 40
}

pozitif_needed_for_customer = {
    'fiat_35_nc': 60,
    'isuzu_24v': 30
}

factories = list(set(i[1] for i in shipping_cost_from_supplier_to_factory.keys()))
suppliers = list(set(i[0] for i in shipping_cost_from_supplier_to_factory.keys()))

model = Model("coal_distribution")

x = model.addVars(shipping_cost_from_supplier_to_factory.keys(), vtype=GRB.INTEGER, name="x")
y_negatif = model.addVars(shipping_cost_from_factory_to_customer.keys(), vtype=GRB.INTEGER, name="y_negatif")
y_pozitif = model.addVars(shipping_cost_from_factory_to_customer.keys(), vtype=GRB.INTEGER, name="y_pozitif")

# === objective ===

model.setObjective(
    sum(x[i] * shipping_cost_from_supplier_to_factory[i] for i in shipping_cost_from_supplier_to_factory.keys()) +
    sum(cost_negatif[r] * y_negatif[r, c] + cost_pozitif[r] * y_pozitif[r, c] for r, c in shipping_cost_from_factory_to_customer.keys()) +
    sum((y_negatif[j] + y_pozitif[j]) * shipping_cost_from_factory_to_customer[j] for j in shipping_cost_from_factory_to_customer.keys()),
    GRB.MINIMIZE
)

# === constraints ===

# Akış koruma kısıtları (fabrikalarda giriş = çıkış)
for r in factories:
    model.addConstr(
        sum(x[i] for i in shipping_cost_from_supplier_to_factory.keys() if i[1] == r) ==
        sum(y_negatif[j] + y_pozitif[j] for j in shipping_cost_from_factory_to_customer.keys() if j[0] == r),
        f"flow_{r}"
    )

# Tedarikçi kapasite kısıtları
for s in suppliers:
    model.addConstr(
        sum(x[i] for i in shipping_cost_from_supplier_to_factory.keys() if i[0] == s) <= capacity_in_supplier[s],
        f"supply_{s}"
    )

# Talep kısıtları
for c in customers:
    model.addConstr(
        sum(y_negatif[j] for j in shipping_cost_from_factory_to_customer.keys() if j[1] == c) >= negatif_needed_for_customer[c],
        f"negatif_demand_{c}"
    )
    model.addConstr(
        sum(y_pozitif[j] for j in shipping_cost_from_factory_to_customer.keys() if j[1] == c) >= pozitif_needed_for_customer[c],
        f"pozitif_demand_{c}"
    )

# === solve ===

model.optimize()

print(time.ctime())
if model.status == GRB.OPTIMAL:
    print(f'Optimal cost: {model.objVal}')
else:
    print("Optimum bulunamadı. Durum kodu:", model.status)