# -*- coding: utf-8 -*-
"""coall.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhiqnnU8smxplbv0iZ3TDIE3OLRBv5ty
"""

from gurobipy import Model, GRB

def solve_coal_distribution(demand_negative, demand_positive):
    # Sabit parametreler
    supplier_capacity = {
        'supplier1': 120,
        'supplier2': 100,
        'supplier3': 80
    }

    factory_capacity = {
        'factory1': 140,
        'factory2': 120
    }

    shipping_sf = {
        ('supplier1', 'factory1'): 4,
        ('supplier1', 'factory2'): 6,
        ('supplier2', 'factory1'): 5,
        ('supplier2', 'factory2'): 3,
        ('supplier3', 'factory1'): 7,
        ('supplier3', 'factory2'): 4
    }

    shipping_fc = {
        ('factory1', 'customer1'): 20,
        ('factory1', 'customer2'): 35,
        ('factory2', 'customer1'): 25,
        ('factory2', 'customer2'): 30
    }

    production_cost_negative = {'factory1': 5, 'factory2': 5}
    production_cost_positive = {'factory1': 8, 'factory2': 8}
    base_cost = {'factory1': 39.39, 'factory2': 39.39}

    # Model oluşturuluyor
    model = Model("Coal_Distribution")
    model.setParam('OutputFlag', 0)  # Konsola gereksiz çıktı basmasın

    # Karar değişkenleri
    x = model.addVars(shipping_sf.keys(), vtype=GRB.INTEGER, name="x")
    y_negative = model.addVars(shipping_fc.keys(), vtype=GRB.INTEGER, name="y_negative")
    y_positive = model.addVars(shipping_fc.keys(), vtype=GRB.INTEGER, name="y_positive")

    # Kısıtlar
    for s in supplier_capacity:
        model.addConstr(sum(x[s, f] for f in factory_capacity) <= supplier_capacity[s], name=f"supplier_capacity_{s}")

    for c in demand_negative:
        model.addConstr(sum(y_negative[f, c] for f in factory_capacity) >= demand_negative[c], name=f"demand_negative_{c}")
        model.addConstr(sum(y_positive[f, c] for f in factory_capacity) >= demand_positive[c], name=f"demand_positive_{c}")

    for f in factory_capacity:
        model.addConstr(
            sum(y_negative[f, c] + y_positive[f, c] for c in demand_negative) <= factory_capacity[f],
            name=f"factory_capacity_{f}"
        )
        model.addConstr(
            sum(x[s, f] for s in supplier_capacity) ==
            sum(y_negative[f, c] + y_positive[f, c] for c in demand_negative),
            name=f"flow_balance_{f}"
        )

    # Amaç fonksiyonu
    model.setObjective(
        sum(shipping_sf[sf] * x[sf] for sf in shipping_sf) +
        sum((shipping_fc[fc] + base_cost[fc[0]] + production_cost_negative[fc[0]]) * y_negative[fc] for fc in shipping_fc) +
        sum((shipping_fc[fc] + base_cost[fc[0]] + production_cost_positive[fc[0]]) * y_positive[fc] for fc in shipping_fc),
        GRB.MINIMIZE
    )

    # Modeli çöz
    model.optimize()

    # Sonuçları döndür
    if model.status == GRB.OPTIMAL:
        result = {
            "objective_value": model.ObjVal,
            "variables": {v.VarName: v.X for v in model.getVars() if v.X > 0}
        }
        return result
    else:
        return {"status": "Infeasible"}

# 🔁 Örnek kullanım:
demand_negative_example = {'customer1': 50, 'customer2': 40}
demand_positive_example = {'customer1': 60, 'customer2': 30}

solution = solve_coal_distribution(demand_negative_example, demand_positive_example)

if "objective_value" in solution:
    print(f"✅ Total cost: {solution['objective_value']:.2f}")
    for name, val in solution["variables"].items():
        print(f"{name}: {val}")
else:
    print("❌ No feasible solution found.")